CREATE TABLE Customer(
   CustomerID   INTEGER  NOT NULL PRIMARY KEY 
  ,CustomerName VARCHAR(13)
  ,Address      VARCHAR(12)
  ,Login        VARCHAR(9)
  ,Password     VARCHAR(9)
  ,Gender       VARCHAR(6)
  ,Email        VARCHAR(23)
  ,Nationality  VARCHAR(13)
  ,IsSuperuser  BOOLEAN  
  ,IsAdmin      BOOLEAN 
);

INSERT INTO Customer(CustomerID,CustomerName,Address,Login,Password,Gender,Email,Nationality,IsSuperuser,IsAdmin) VALUES (10000,'administrator','address0','admin','admin','Male','admin@admin.com','lebanese',false,true);
INSERT INTO Customer(CustomerID,CustomerName,Address,Login,Password,Gender,Email,Nationality,IsSuperuser,IsAdmin) VALUES (10001,'superuser','address1','superuser','superuser','Female','superuser@superuser.com','lebanese',true,false);
INSERT INTO Customer(CustomerID,CustomerName,Address,Login,Password,Gender,Email,Nationality,IsSuperuser,IsAdmin) VALUES (10002,'user1','address1','login1','login1','Male','user1@gmail.com','nationality1',false,false);
INSERT INTO Customer(CustomerID,CustomerName,Address,Login,Password,Gender,Email,Nationality,IsSuperuser,IsAdmin) VALUES (10003,'user2','address2','login2','login2','Male','user2@gmail.com','nationality2',false,false);
INSERT INTO Customer(CustomerID,CustomerName,Address,Login,Password,Gender,Email,Nationality,IsSuperuser,IsAdmin) VALUES (10004,'user3','address3','login3','login3','Male','user3@gmail.com','nationality3',false,false);
INSERT INTO Customer(CustomerID,CustomerName,Address,Login,Password,Gender,Email,Nationality,IsSuperuser,IsAdmin) VALUES (10005,'user4','address4','login4','login4','Male','user4@gmail.com','nationality4',false,false);
INSERT INTO Customer(CustomerID,CustomerName,Address,Login,Password,Gender,Email,Nationality,IsSuperuser,IsAdmin) VALUES (10006,'user5','address5','login5','login5','Male','user5@gmail.com','nationality5',false,false);
INSERT INTO Customer(CustomerID,CustomerName,Address,Login,Password,Gender,Email,Nationality,IsSuperuser,IsAdmin) VALUES (10007,'user6','address6','login6','login6','Male','user6@gmail.com','nationality6',false,false);
INSERT INTO Customer(CustomerID,CustomerName,Address,Login,Password,Gender,Email,Nationality,IsSuperuser,IsAdmin) VALUES (10008,'user7','address7','login7','login7','Male','user7@gmail.com','nationality7',false,false);
INSERT INTO Customer(CustomerID,CustomerName,Address,Login,Password,Gender,Email,Nationality,IsSuperuser,IsAdmin) VALUES (10009,'user8','address8','login8','login8','Male','user8@gmail.com','nationality8',false,false);
INSERT INTO Customer(CustomerID,CustomerName,Address,Login,Password,Gender,Email,Nationality,IsSuperuser,IsAdmin) VALUES (10010,'user9','address9','login9','login9','Male','user9@gmail.com','nationality9',false,false);
INSERT INTO Customer(CustomerID,CustomerName,Address,Login,Password,Gender,Email,Nationality,IsSuperuser,IsAdmin) VALUES (10011,'user10','address10','login10','login10','Male','user10@gmail.com','nationality10',false,false);
INSERT INTO Customer(CustomerID,CustomerName,Address,Login,Password,Gender,Email,Nationality,IsSuperuser,IsAdmin) VALUES (10012,'user11','address11','login11','login11','Male','user11@gmail.com','nationality11',false,false);
INSERT INTO Customer(CustomerID,CustomerName,Address,Login,Password,Gender,Email,Nationality,IsSuperuser,IsAdmin) VALUES (10013,'user12fff','address12fff','login12f','login12','Male','user12@gmail.com','nationality12',false,false);
INSERT INTO Customer(CustomerID,CustomerName,Address,Login,Password,Gender,Email,Nationality,IsSuperuser,IsAdmin) VALUES (10014,'user13','address13','login13','login13','Male','user13@gmail.com','nationality13',false,false);
INSERT INTO Customer(CustomerID,CustomerName,Address,Login,Password,Gender,Email,Nationality,IsSuperuser,IsAdmin) VALUES (10015,'user14','address14','login14','login14','Male','user14@gmail.com','nationality14',false,false);
INSERT INTO Customer(CustomerID,CustomerName,Address,Login,Password,Gender,Email,Nationality,IsSuperuser,IsAdmin) VALUES (10016,'user15','address15','login15','login15','Male','user15@gmail.com','nationality15',false,false);
INSERT INTO Customer(CustomerID,CustomerName,Address,Login,Password,Gender,Email,Nationality,IsSuperuser,IsAdmin) VALUES (10017,'user16','address16','login16','login16','Male','user16@gmail.com','nationality16',false,false);
INSERT INTO Customer(CustomerID,CustomerName,Address,Login,Password,Gender,Email,Nationality,IsSuperuser,IsAdmin) VALUES (10018,'user17','address17','login17','login17','Male','user17@gmail.com','nationality17',false,false);
INSERT INTO Customer(CustomerID,CustomerName,Address,Login,Password,Gender,Email,Nationality,IsSuperuser,IsAdmin) VALUES (10019,'user18','address18','login18','login18','Male','user18@gmail.com','nationality18',false,false);
INSERT INTO Customer(CustomerID,CustomerName,Address,Login,Password,Gender,Email,Nationality,IsSuperuser,IsAdmin) VALUES (10020,'user19','address19','login19','login19','Male','user19@gmail.com','nationality19',false,false);
INSERT INTO Customer(CustomerID,CustomerName,Address,Login,Password,Gender,Email,Nationality,IsSuperuser,IsAdmin) VALUES (10021,'user20','address20','login20','login20','Male','user20@gmail.com','nationality20',false,false);
INSERT INTO Customer(CustomerID,CustomerName,Address,Login,Password,Gender,Email,Nationality,IsSuperuser,IsAdmin) VALUES (10022,'user21','address21','login21','login21','Male','user21@gmail.com','nationality21',false,false);
INSERT INTO Customer(CustomerID,CustomerName,Address,Login,Password,Gender,Email,Nationality,IsSuperuser,IsAdmin) VALUES (10023,'user22','address22','login22','login22','Male','user22@gmail.com','nationality22',false,false);
INSERT INTO Customer(CustomerID,CustomerName,Address,Login,Password,Gender,Email,Nationality,IsSuperuser,IsAdmin) VALUES (10024,'user23','address23','login23','login23','Male','user23@gmail.com','nationality23',false,false);
INSERT INTO Customer(CustomerID,CustomerName,Address,Login,Password,Gender,Email,Nationality,IsSuperuser,IsAdmin) VALUES (10025,'user24','address24','login24','login24','Male','user24@gmail.com','nationality24',false,false);
INSERT INTO Customer(CustomerID,CustomerName,Address,Login,Password,Gender,Email,Nationality,IsSuperuser,IsAdmin) VALUES (10026,'user25','address25','login25','login25','Male','user25@gmail.com','nationality25',false,false);
INSERT INTO Customer(CustomerID,CustomerName,Address,Login,Password,Gender,Email,Nationality,IsSuperuser,IsAdmin) VALUES (10027,'user26','address26','login26','login26','Male','user26@gmail.com','nationality26',false,false);
INSERT INTO Customer(CustomerID,CustomerName,Address,Login,Password,Gender,Email,Nationality,IsSuperuser,IsAdmin) VALUES (10028,'user27','address27','login27','login27','Male','user27@gmail.com','nationality27',false,false);
INSERT INTO Customer(CustomerID,CustomerName,Address,Login,Password,Gender,Email,Nationality,IsSuperuser,IsAdmin) VALUES (10029,'user28','address28','login28','login28','Male','user28@gmail.com','nationality28',false,false);
INSERT INTO Customer(CustomerID,CustomerName,Address,Login,Password,Gender,Email,Nationality,IsSuperuser,IsAdmin) VALUES (10030,'user29','address29','login29','login29','Male','user29@gmail.com','nationality29',false,false);
INSERT INTO Customer(CustomerID,CustomerName,Address,Login,Password,Gender,Email,Nationality,IsSuperuser,IsAdmin) VALUES (10031,'user30','address30','login30','login30','Male','user30@gmail.com','nationality30',false,false);
INSERT INTO Customer(CustomerID,CustomerName,Address,Login,Password,Gender,Email,Nationality,IsSuperuser,IsAdmin) VALUES (10032,'user31','address31','login31','login31','Male','user31@gmail.com','nationality31',false,false);
INSERT INTO Customer(CustomerID,CustomerName,Address,Login,Password,Gender,Email,Nationality,IsSuperuser,IsAdmin) VALUES (10033,'user32','address32','login32','login32','Male','user32@gmail.com','nationality32',false,false);
INSERT INTO Customer(CustomerID,CustomerName,Address,Login,Password,Gender,Email,Nationality,IsSuperuser,IsAdmin) VALUES (10034,'user33','address33','login33','login33','Male','user33@gmail.com','nationality33',false,false);
INSERT INTO Customer(CustomerID,CustomerName,Address,Login,Password,Gender,Email,Nationality,IsSuperuser,IsAdmin) VALUES (10035,'user34','address34','login34','login34','Male','user34@gmail.com','nationality34',false,false);
INSERT INTO Customer(CustomerID,CustomerName,Address,Login,Password,Gender,Email,Nationality,IsSuperuser,IsAdmin) VALUES (10036,'user35','address35','login35','login35','Male','user35@gmail.com','nationality35',false,false);
INSERT INTO Customer(CustomerID,CustomerName,Address,Login,Password,Gender,Email,Nationality,IsSuperuser,IsAdmin) VALUES (10037,'user36','address36','login36','login36','Male','user36@gmail.com','nationality36',false,false);
INSERT INTO Customer(CustomerID,CustomerName,Address,Login,Password,Gender,Email,Nationality,IsSuperuser,IsAdmin) VALUES (10038,'user37','address37','login37','login37','Male','user37@gmail.com','nationality37',false,false);
INSERT INTO Customer(CustomerID,CustomerName,Address,Login,Password,Gender,Email,Nationality,IsSuperuser,IsAdmin) VALUES (10039,'user38','address38','login38','login38','Male','user38@gmail.com','nationality38',false,false);
INSERT INTO Customer(CustomerID,CustomerName,Address,Login,Password,Gender,Email,Nationality,IsSuperuser,IsAdmin) VALUES (10040,'user39','address39','login39','login39','Male','user39@gmail.com','nationality39',false,false);
INSERT INTO Customer(CustomerID,CustomerName,Address,Login,Password,Gender,Email,Nationality,IsSuperuser,IsAdmin) VALUES (10041,'user40','address40','login40','login40','Male','user40@gmail.com','nationality40',false,false);
INSERT INTO Customer(CustomerID,CustomerName,Address,Login,Password,Gender,Email,Nationality,IsSuperuser,IsAdmin) VALUES (10042,'user41','address41','login41','login41','Male','user41@gmail.com','nationality41',false,false);
INSERT INTO Customer(CustomerID,CustomerName,Address,Login,Password,Gender,Email,Nationality,IsSuperuser,IsAdmin) VALUES (10043,'user42','address42','login42','login42','Male','user42@gmail.com','nationality42',false,false);
INSERT INTO Customer(CustomerID,CustomerName,Address,Login,Password,Gender,Email,Nationality,IsSuperuser,IsAdmin) VALUES (10044,'user43','address43','login43','login43','Male','user43@gmail.com','nationality43',false,false);
INSERT INTO Customer(CustomerID,CustomerName,Address,Login,Password,Gender,Email,Nationality,IsSuperuser,IsAdmin) VALUES (10045,'user44','address44','login44','login44','Male','user44@gmail.com','nationality44',false,false);
INSERT INTO Customer(CustomerID,CustomerName,Address,Login,Password,Gender,Email,Nationality,IsSuperuser,IsAdmin) VALUES (10046,'user45','address45','login45','login45','Male','user45@gmail.com','nationality45',false,false);
INSERT INTO Customer(CustomerID,CustomerName,Address,Login,Password,Gender,Email,Nationality,IsSuperuser,IsAdmin) VALUES (10047,'user46','address46','login46','login46','Male','user46@gmail.com','nationality46',false,false);
INSERT INTO Customer(CustomerID,CustomerName,Address,Login,Password,Gender,Email,Nationality,IsSuperuser,IsAdmin) VALUES (10048,'user47','address47','login47','login47','Male','user47@gmail.com','nationality47',false,false);
INSERT INTO Customer(CustomerID,CustomerName,Address,Login,Password,Gender,Email,Nationality,IsSuperuser,IsAdmin) VALUES (10049,'user48','address48','login48','login48','Male','user48@gmail.com','nationality48',false,false);
INSERT INTO Customer(CustomerID,CustomerName,Address,Login,Password,Gender,Email,Nationality,IsSuperuser,IsAdmin) VALUES (10050,'user49','address49','login49','login49','Male','user49@gmail.com','nationality49',false,false);
INSERT INTO Customer(CustomerID,CustomerName,Address,Login,Password,Gender,Email,Nationality,IsSuperuser,IsAdmin) VALUES (10051,'user50','address50','login50','login50','Male','user50@gmail.com','nationality50',false,false);
INSERT INTO Customer(CustomerID,CustomerName,Address,Login,Password,Gender,Email,Nationality,IsSuperuser,IsAdmin) VALUES (10052,'user51','address51','login51','login51','Male','user51@gmail.com','nationality51',false,false);
INSERT INTO Customer(CustomerID,CustomerName,Address,Login,Password,Gender,Email,Nationality,IsSuperuser,IsAdmin) VALUES (10053,'user52','address52','login52','login52','Male','user52@gmail.com','nationality52',false,false);
INSERT INTO Customer(CustomerID,CustomerName,Address,Login,Password,Gender,Email,Nationality,IsSuperuser,IsAdmin) VALUES (10054,'user53','address53','login53','login53','Male','user53@gmail.com','nationality53',false,false);
INSERT INTO Customer(CustomerID,CustomerName,Address,Login,Password,Gender,Email,Nationality,IsSuperuser,IsAdmin) VALUES (10055,'user54','address54','login54','login54','Male','user54@gmail.com','nationality54',false,false);
INSERT INTO Customer(CustomerID,CustomerName,Address,Login,Password,Gender,Email,Nationality,IsSuperuser,IsAdmin) VALUES (10056,'user55','address55','login55','login55','Male','user55@gmail.com','nationality55',false,false);
INSERT INTO Customer(CustomerID,CustomerName,Address,Login,Password,Gender,Email,Nationality,IsSuperuser,IsAdmin) VALUES (10057,'user56','address56','login56','login56','Male','user56@gmail.com','nationality56',false,false);
INSERT INTO Customer(CustomerID,CustomerName,Address,Login,Password,Gender,Email,Nationality,IsSuperuser,IsAdmin) VALUES (10058,'user57','address57','login57','login57','Male','user57@gmail.com','nationality57',false,false);
INSERT INTO Customer(CustomerID,CustomerName,Address,Login,Password,Gender,Email,Nationality,IsSuperuser,IsAdmin) VALUES (10059,'user58','address58','login58','login58','Male','user58@gmail.com','nationality58',false,false);
INSERT INTO Customer(CustomerID,CustomerName,Address,Login,Password,Gender,Email,Nationality,IsSuperuser,IsAdmin) VALUES (10060,'user59','address59','login59','login59','Male','user59@gmail.com','nationality59',false,false);
INSERT INTO Customer(CustomerID,CustomerName,Address,Login,Password,Gender,Email,Nationality,IsSuperuser,IsAdmin) VALUES (10061,'user60','address60','login60','login60','Male','user60@gmail.com','nationality60',false,false);
INSERT INTO Customer(CustomerID,CustomerName,Address,Login,Password,Gender,Email,Nationality,IsSuperuser,IsAdmin) VALUES (10062,'user61','address61','login61','login61','Male','user61@gmail.com','nationality61',false,false);
INSERT INTO Customer(CustomerID,CustomerName,Address,Login,Password,Gender,Email,Nationality,IsSuperuser,IsAdmin) VALUES (10063,'user62','address62','login62','login62','Male','user62@gmail.com','nationality62',false,false);
INSERT INTO Customer(CustomerID,CustomerName,Address,Login,Password,Gender,Email,Nationality,IsSuperuser,IsAdmin) VALUES (10064,'user63','address63','login63','login63','Male','user63@gmail.com','nationality63',false,false);
INSERT INTO Customer(CustomerID,CustomerName,Address,Login,Password,Gender,Email,Nationality,IsSuperuser,IsAdmin) VALUES (10065,'user64','address64','login64','login64','Male','user64@gmail.com','nationality64',false,false);
INSERT INTO Customer(CustomerID,CustomerName,Address,Login,Password,Gender,Email,Nationality,IsSuperuser,IsAdmin) VALUES (10066,'user65','address65','login65','login65','Male','user65@gmail.com','nationality65',false,false);
INSERT INTO Customer(CustomerID,CustomerName,Address,Login,Password,Gender,Email,Nationality,IsSuperuser,IsAdmin) VALUES (10067,'user66','address66','login66','login66','Male','user66@gmail.com','nationality66',false,false);
INSERT INTO Customer(CustomerID,CustomerName,Address,Login,Password,Gender,Email,Nationality,IsSuperuser,IsAdmin) VALUES (10068,'user67','address67','login67','login67','Male','user67@gmail.com','nationality67',false,false);
INSERT INTO Customer(CustomerID,CustomerName,Address,Login,Password,Gender,Email,Nationality,IsSuperuser,IsAdmin) VALUES (10069,'user68','address68','login68','login68','Male','user68@gmail.com','nationality68',false,false);
INSERT INTO Customer(CustomerID,CustomerName,Address,Login,Password,Gender,Email,Nationality,IsSuperuser,IsAdmin) VALUES (10070,'user69','address69','login69','login69','Male','user69@gmail.com','nationality69',false,false);
INSERT INTO Customer(CustomerID,CustomerName,Address,Login,Password,Gender,Email,Nationality,IsSuperuser,IsAdmin) VALUES (10071,'user70','address70','login70','login70','Male','user70@gmail.com','nationality70',false,false);
INSERT INTO Customer(CustomerID,CustomerName,Address,Login,Password,Gender,Email,Nationality,IsSuperuser,IsAdmin) VALUES (10072,'user71','address71','login71','login71','Male','user71@gmail.com','nationality71',false,false);
INSERT INTO Customer(CustomerID,CustomerName,Address,Login,Password,Gender,Email,Nationality,IsSuperuser,IsAdmin) VALUES (10073,'user72','address72','login72','login72','Male','user72@gmail.com','nationality72',false,false);
INSERT INTO Customer(CustomerID,CustomerName,Address,Login,Password,Gender,Email,Nationality,IsSuperuser,IsAdmin) VALUES (10074,'user73','address73','login73','login73','Male','user73@gmail.com','nationality73',false,false);
INSERT INTO Customer(CustomerID,CustomerName,Address,Login,Password,Gender,Email,Nationality,IsSuperuser,IsAdmin) VALUES (10075,'user74','address74','login74','login74','Male','user74@gmail.com','nationality74',false,false);
INSERT INTO Customer(CustomerID,CustomerName,Address,Login,Password,Gender,Email,Nationality,IsSuperuser,IsAdmin) VALUES (10076,'user75','address75','login75','login75','Male','user75@gmail.com','nationality75',false,false);
INSERT INTO Customer(CustomerID,CustomerName,Address,Login,Password,Gender,Email,Nationality,IsSuperuser,IsAdmin) VALUES (10077,'user76','address76','login76','login76','Male','user76@gmail.com','nationality76',false,false);
INSERT INTO Customer(CustomerID,CustomerName,Address,Login,Password,Gender,Email,Nationality,IsSuperuser,IsAdmin) VALUES (10078,'user77','address77','login77','login77','Male','user77@gmail.com','nationality77',false,false);
INSERT INTO Customer(CustomerID,CustomerName,Address,Login,Password,Gender,Email,Nationality,IsSuperuser,IsAdmin) VALUES (10079,'user78','address78','login78','login78','Male','user78@gmail.com','nationality78',false,false);
INSERT INTO Customer(CustomerID,CustomerName,Address,Login,Password,Gender,Email,Nationality,IsSuperuser,IsAdmin) VALUES (10080,'user79','address79','login79','login79','Male','user79@gmail.com','nationality79',false,false);
INSERT INTO Customer(CustomerID,CustomerName,Address,Login,Password,Gender,Email,Nationality,IsSuperuser,IsAdmin) VALUES (10081,'user80','address80','login80','login80','Male','user80@gmail.com','nationality80',false,false);
INSERT INTO Customer(CustomerID,CustomerName,Address,Login,Password,Gender,Email,Nationality,IsSuperuser,IsAdmin) VALUES (10082,'user81','address81','login81','login81','Male','user81@gmail.com','nationality81',false,false);
INSERT INTO Customer(CustomerID,CustomerName,Address,Login,Password,Gender,Email,Nationality,IsSuperuser,IsAdmin) VALUES (10083,'user82','address82','login82','login82','Male','user82@gmail.com','nationality82',false,false);
INSERT INTO Customer(CustomerID,CustomerName,Address,Login,Password,Gender,Email,Nationality,IsSuperuser,IsAdmin) VALUES (10084,'user83','address83','login83','login83','Male','user83@gmail.com','nationality83',false,false);
INSERT INTO Customer(CustomerID,CustomerName,Address,Login,Password,Gender,Email,Nationality,IsSuperuser,IsAdmin) VALUES (10085,'user84','address84','login84','login84','Male','user84@gmail.com','nationality84',false,false);
INSERT INTO Customer(CustomerID,CustomerName,Address,Login,Password,Gender,Email,Nationality,IsSuperuser,IsAdmin) VALUES (10086,'user85','address85','login85','login85','Male','user85@gmail.com','nationality85',false,false);
INSERT INTO Customer(CustomerID,CustomerName,Address,Login,Password,Gender,Email,Nationality,IsSuperuser,IsAdmin) VALUES (10087,'user86','address86','login86','login86','Male','user86@gmail.com','nationality86',false,false);
INSERT INTO Customer(CustomerID,CustomerName,Address,Login,Password,Gender,Email,Nationality,IsSuperuser,IsAdmin) VALUES (10088,'user87','address87','login87','login87','Male','user87@gmail.com','nationality87',false,false);
INSERT INTO Customer(CustomerID,CustomerName,Address,Login,Password,Gender,Email,Nationality,IsSuperuser,IsAdmin) VALUES (10089,'user88','address88','login88','login88','Male','user88@gmail.com','nationality88',false,false);
INSERT INTO Customer(CustomerID,CustomerName,Address,Login,Password,Gender,Email,Nationality,IsSuperuser,IsAdmin) VALUES (10090,'user89','address89','login89','login89','Male','user89@gmail.com','nationality89',false,false);
INSERT INTO Customer(CustomerID,CustomerName,Address,Login,Password,Gender,Email,Nationality,IsSuperuser,IsAdmin) VALUES (10091,'user90','address90','login90','login90','Male','user90@gmail.com','nationality90',false,false);
INSERT INTO Customer(CustomerID,CustomerName,Address,Login,Password,Gender,Email,Nationality,IsSuperuser,IsAdmin) VALUES (10092,'user91','address91','login91','login91','Male','user91@gmail.com','nationality91',false,false);
INSERT INTO Customer(CustomerID,CustomerName,Address,Login,Password,Gender,Email,Nationality,IsSuperuser,IsAdmin) VALUES (10093,'user92','address92','login92','login92','Male','user92@gmail.com','nationality92',false,false);
INSERT INTO Customer(CustomerID,CustomerName,Address,Login,Password,Gender,Email,Nationality,IsSuperuser,IsAdmin) VALUES (10094,'user93','address93','login93','login93','Male','user93@gmail.com','nationality93',false,false);
INSERT INTO Customer(CustomerID,CustomerName,Address,Login,Password,Gender,Email,Nationality,IsSuperuser,IsAdmin) VALUES (10095,'user94','address94','login94','login94','Male','user94@gmail.com','nationality94',false,false);
INSERT INTO Customer(CustomerID,CustomerName,Address,Login,Password,Gender,Email,Nationality,IsSuperuser,IsAdmin) VALUES (10096,'user95','address95','login95','login95','Male','user95@gmail.com','nationality95',false,false);
INSERT INTO Customer(CustomerID,CustomerName,Address,Login,Password,Gender,Email,Nationality,IsSuperuser,IsAdmin) VALUES (10097,'user96','address96','login96','login96','Male','user96@gmail.com','nationality96',false,false);
INSERT INTO Customer(CustomerID,CustomerName,Address,Login,Password,Gender,Email,Nationality,IsSuperuser,IsAdmin) VALUES (10098,'user97','address97','login97','login97','Male','user97@gmail.com','nationality97',false,false);
INSERT INTO Customer(CustomerID,CustomerName,Address,Login,Password,Gender,Email,Nationality,IsSuperuser,IsAdmin) VALUES (10099,'user98','address98','login98','login98','Male','user98@gmail.com','nationality98',false,false);
INSERT INTO Customer(CustomerID,CustomerName,Address,Login,Password,Gender,Email,Nationality,IsSuperuser,IsAdmin) VALUES (10100,'user99','address99','login99','login99','Male','user99@gmail.com','nationality99',false,false);
